name: publish v8 macOS libraries to release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'release tag'
        required: true
        type: string
  
jobs:
  build-v8:
    runs-on: macos-14
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: test zip files
        run: |
          mkdir test_folder
          zip -r lynx_test_release_1204_1.zip test_folder
      - name: push to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "lynx_test_release_1204_1.zip"
      - name: publish to maven
        env:
          PORTAL_API_USERNAME: ${{ secrets.PORTAL_API_USERNAME }}
          PORTAL_API_TOKEN: ${{ secrets.PORTAL_API_TOKEN }}
        run: |
          echo $PORTAL_API_USERNAME
          echo $PORTAL_API_TOKEN
          curl --request POST \
          --verbose \
          -u $PORTAL_API_USERNAME:$PORTAL_API_TOKEN \
          --form zipfile=@lynx_test_release_1204_1.zip \
          https://central.sonatype.com/api/v1/publisher/upload
